"""Add Razorpay fields

Revision ID: 81968c16c8b9
Revises: ff2b36bc899d
Create Date: 2026-02-17 15:53:21.211210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81968c16c8b9'
down_revision: Union[str, Sequence[str], None] = 'ff2b36bc899d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('razorpay_signature', sa.String(), nullable=True))
    op.add_column('enrollments', sa.Column('paid_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'paid_amount')
    op.drop_column('enrollments', 'razorpay_signature')
    op.drop_column('enrollments', 'razorpay_payment_id')
    op.drop_column('enrollments', 'razorpay_order_id')
    # ### end Alembic commands ###
